apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nwrjsgmwl-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nwrjsgmwl-java-quarkus-gitops